[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "DeepLearningDevelopment"
version = "0.1.2"
description = "Personal Deep Learning Module"
authors = [{name = "Sisung Kim"}]
dependencies = [
    "numpy>=1,<2",
    "torch>=2,<3",
]
